export const GET_CATEGORIES_LIST_PENDING = "GET_CATEGORIES_LIST_PENDING";
export const GET_CATEGORIES_LIST_RESOLVED = "GET_CATEGORIES_LIST_RESOLVED";
export const GET_CATEGORIES_LIST_REJECTED = "GET_CATEGORIES_LIST_REJECTED";
export const GET_LIST_COCKTAILS_FILTERED_PENDING = "GET_LIST_COCKTAILS_FILTERED_PENDING";
export const GET_LIST_COCKTAILS_FILTERED_RESOLVED = "GET_LIST_COCKTAILS_FILTERED_RESOLVED";
export const GET_LIST_COCKTAILS_FILTERED_REJECTED = "GET_LIST_COCKTAILS_FILTERED_REJECTED";
export const SET_FILTERS = "SET_FILTERS";

