export const GET_CATEGORIES_LIST_PENDING = "GET_CATEGORIES_LIST_PENDING";
export const GET_CATEGORIES_LIST_RESOLVED = "GET_CATEGORIES_LIST_RESOLVED";
export const GET_CATEGORIES_LIST_REJECTED = "GET_CATEGORIES_LIST_REJECTED";
export const GET_LIST_COCKTAILS_FILTERED_PENDING = "GET_LIST_COCKTAILS_FILTERED_PENDING";
export const GET_LIST_COCKTAILS_FILTERED_RESOLVED = "GET_LIST_COCKTAILS_FILTERED_RESOLVED";
export const GET_LIST_COCKTAILS_FILTERED_REJECTED = "GET_LIST_COCKTAILS_FILTERED_REJECTED";
export const GET_NEXT_ITEM_CATEGORIES_PENDING = "GET_NEXT_ITEM_CATEGORIES_PENDING";
export const GET_NEXT_ITEM_CATEGORIES_RESOLVED = "GET_NEXT_ITEM_CATEGORIES_RESOLVED";
export const GET_NEXT_ITEM_CATEGORIES_REJECTED = "GET_NEXT_ITEM_CATEGORIES_REJECTED";
export const SET_EMPTY_LIST_CATEGORIES = "SET_EMPTY_LIST_CATEGORIES";
export const SET_FILTERS = "SET_FILTERS";

